[build]
target="riscv64gc-unknown-none-elf"
rustflags=['-Clink-arg=-Tsrc/virt.lds']
[target.riscv64gc-unknown-none-elf]
runner ="qemu-system-riscv64 -machine virt -cpu rv64 -smp 1 -m 128M -drive if=none,format=raw,file=hdd.dsk,id=foo -nographic -serial mon:stdio -bios none -device virtio-rng-device -device virtio-gpu-device -device virtio-net-device -device virtio-tablet-device -device virtio-keyboard-device -kernel"
